sudo: required
services:
  - docker

before_install:
  - docker build -t muzmov/webnotes-test -f Dockerfile.test .

script:
  - docker run muzmov/webnotes-test

after_success:
  - docker build -t muzmov/webnotes .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "webnotes"
  env: "webnotes-environment"
  bucket_name: "elasticbeanstalk-us-east-2-995459693010"
  bucket_path: "webnotes"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"