sudo: required
services:
  - docker

before_install:
  - docker build -t muzmov/webnotes-test -f Dockerfile.test .

script:
  - docker run muzmov/webnotes-test

after_success:
  - docker build -t muzmov/webnotes .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push muzmov/webnotes

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "notes"
  env: "notes-env"
  bucket_name: "elasticbeanstalk-us-east-2-995459693010"
  bucket_path: "notes"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"