version: '3'
services:
  postgres:
    image: postgres:10.7-alpine
    ports:
      - 5433:5432
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres_password
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080:8080