version: '3'
services:
  postgres:
    image: postgres:10.7-alpine
    ports:
      - 5433:5432
  server:
    build:
      context: .
    environment:
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=postgres_password
      - RDS_HOSTNAME=postgres
      - RDS_PORT=5432
      - RDS_DB_NAME=postgres
    ports:
      - 8080:8080