apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        version: v1
    spec:
      containers:
        - name: auth
          image: muzmov/webnotes-auth
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: RDS_USERNAME
              value: postgres
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: RDS_HOSTNAME
              value: postgres-user
            - name: RDS_PORT
              value: "5432"
            - name: RDS_DB_NAME
              value: postgres
            - name: SECURITY_SIGN_KEY
              valueFrom:
                secretKeyRef:
                  name: security-sign-key
                  key: SECURITY_SIGN_KEY